language: python
python:
  - "3.5"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda env create -f environment.yml -n test-environment
  - source activate test-environment
  - python setup.py sdist
  - pip install dist/tefingerprint-*.tar.gz
script: python -m pytest -vv ./
